# Imagen base de ASP.NET 8 para runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80

# Imagen SDK de .NET 8 para compilar el proyecto
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["KioscoAPI/KioscoAPI.csproj", "KioscoAPI/"]
RUN dotnet restore "KioscoAPI/KioscoAPI.csproj"
COPY . .
WORKDIR "/src/KioscoAPI"
RUN dotnet build "KioscoAPI.csproj" -c Release -o /app/build

# Publicación del proyecto
FROM build AS publish
RUN dotnet publish "KioscoAPI.csproj" -c Release -o /app/publish

# Imagen final para correr la aplicación
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "KioscoAPI.dll"]